# Generated by Django 3.1 on 2022-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220308_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='tt', upload_to=''),
            preserve_default=False,
        ),
    ]
