# Generated by Django 3.1 on 2022-03-24 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='posted_by',
        ),
    ]
