# Generated by Django 3.1 on 2022-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20220410_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='clothes_type',
            field=models.CharField(blank=True, choices=[('Male Wear', 'Male Wear'), ('Female Wear', 'Female Wear')], max_length=12),
        ),
    ]
