# Generated by Django 3.1 on 2022-04-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20220412_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_number',
            field=models.CharField(default=988736633333, max_length=15),
            preserve_default=False,
        ),
    ]
